### ISSUE TITLE
How to download all historical data for 1m timeframe

### ISSUE THREAD

**Issue by LaeCode** [uoshvis/python-cryptowatch#5]
Hi Guys, 

Im can´t to download all historical data using the API, with a subscription account in Cryptowatch, beside that, i dont find one example where you use the params after or before, could you please add one example to documentation using after and before params

Thanks!

**Comment by uoshvis** [comment]
Hi,

This is an example of how to fetch data for 30 days using `after` and `before` params (both must be integers of Unix timestamp)

```
from cryptowatch.api_client import Client
from datetime import datetime, timedelta
client = Client()

# Returns a market's OHLC candlestick data
# This represents a 1-day candle starting at 30 days ago and ending at the current time

now = datetime.now()
monthAgo = (now - timedelta(days=30))
nowEpoch = int(now.timestamp())
monthAgoEpoch = int(monthAgo.timestamp())

data = {
    'exchange': 'gdax',
    'pair': 'btcusd',
    'route': 'ohlc',
    'params': {
        'before': nowEpoch,
        'after': monthAgoEpoch,
        'periods': '86400'}
}

market = client.get_markets(data=data)
```

Also, I'm not sure if there is an endpoint for all historical data. Choose your time periods using `after` and `before` params.
