### ISSUE TITLE
Using client.get_markets() to obtain ohlc data

### ISSUE THREAD

**Issue by Clayfigure** [uoshvis/python-cryptowatch#9]
I want to use client.get_markets() to obtain ohlc data in a specific time period.
However, the return data was empty.
I wonder why this happen?

My code is listed as below:
data = {
    'exchange': 'binance',
    'pair': 'ethbtc',
    'route': 'ohlc',
    'params': {
        # 'after': "1 Dec, 2021", #1640995200000
        # 'before': "1 Jan, 2022", #1638316800000
        'before': 1517529600,
        'since': 1517616000,
        'periods': '86400'}
}

market = Client.get_markets(data=data)

Could anyone help me?

**Comment by uoshvis** [comment]
Hi, 

this could happen because your end timestamp is smaller than the start timestamp.

Try these params:

```
{
            'before': 1517616000,
            'after': 1517529600,
            'periods': '86400'
}
```

You should get the data.
